# Generated by Django 4.1.2 on 2023-10-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0004_remove_farmproduct_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmApp.buyer')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmApp.seller')),
            ],
        ),
    ]
