# Generated by Django 4.1.2 on 2023-10-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0006_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
