# Generated by Django 4.1.2 on 2023-10-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0009_alter_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(default='buyer', max_length=255),
        ),
    ]
