# Generated by Django 4.1.2 on 2023-10-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0013_chat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
