# Generated by Django 4.1.2 on 2023-10-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0015_remove_seller_address_remove_seller_phoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmproduct',
            name='cost',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
