# Generated by Django 4.2.6 on 2023-10-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0016_farmproduct_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(default='Chennai', max_length=100),
        ),
    ]
