# Generated by Django 4.2.6 on 2023-10-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0017_seller_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='location',
            field=models.CharField(default='Chennai', max_length=100),
        ),
    ]
